/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.Gregorys2s.view.inicializacao;

import com.github.Gregorys2s.controller.CardapioController;
import com.github.Gregorys2s.controller.PedidosController;
import com.github.Gregorys2s.view.cardapio.CardapioFrame;
import com.github.Gregorys2s.view.pedidos.MenuPedidos;

import javax.swing.*;
import java.util.logging.Logger;

/**
 *
 * @author necro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(MenuPrincipal.class.getName());
    private CardapioController cardapiocontroller;
    private PedidosController pedidoscontroller;

    /**
     * Creates new form MenuPrincipall
     */
    public MenuPrincipal(CardapioController cardapiocontroller,PedidosController pedidoscontroller) {
        this.cardapiocontroller = cardapiocontroller;
        this.pedidoscontroller = pedidoscontroller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        cardapioBttn = new javax.swing.JToggleButton();
        estoqueBttn = new javax.swing.JToggleButton();
        relatoriosBttn = new javax.swing.JToggleButton();
        caixaBttn = new javax.swing.JToggleButton();
        sairBttn = new javax.swing.JToggleButton();
        pediddosBttn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardapioBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cardapioBttn.setText("Cardapio");
        cardapioBttn.setToolTipText("");
        cardapioBttn.setAutoscrolls(true);
        cardapioBttn.setBorder(null);
        cardapioBttn.setBorderPainted(false);
        cardapioBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cardapioBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        cardapioBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        cardapioBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        cardapioBttn.addActionListener(this::cardapioBttnActionPerformed);

        estoqueBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        estoqueBttn.setText("Estoque");
        estoqueBttn.setToolTipText("");
        estoqueBttn.setAutoscrolls(true);
        estoqueBttn.setBorder(null);
        estoqueBttn.setBorderPainted(false);
        estoqueBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estoqueBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        estoqueBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        estoqueBttn.setPreferredSize(new java.awt.Dimension(200, 50));

        relatoriosBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        relatoriosBttn.setText("Relatorios");
        relatoriosBttn.setToolTipText("");
        relatoriosBttn.setAutoscrolls(true);
        relatoriosBttn.setBorder(null);
        relatoriosBttn.setBorderPainted(false);
        relatoriosBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        relatoriosBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        relatoriosBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        relatoriosBttn.setPreferredSize(new java.awt.Dimension(200, 50));

        caixaBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caixaBttn.setText("Caixa");
        caixaBttn.setToolTipText("");
        caixaBttn.setAutoscrolls(true);
        caixaBttn.setBorder(null);
        caixaBttn.setBorderPainted(false);
        caixaBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caixaBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        caixaBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        caixaBttn.setPreferredSize(new java.awt.Dimension(200, 50));

        sairBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sairBttn.setText("Sair");
        sairBttn.setToolTipText("");
        sairBttn.setAutoscrolls(true);
        sairBttn.setBorder(null);
        sairBttn.setBorderPainted(false);
        sairBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sairBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        sairBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        sairBttn.setPreferredSize(new java.awt.Dimension(200, 50));

        pediddosBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pediddosBttn.setText("Pedidos");
        pediddosBttn.setToolTipText("");
        pediddosBttn.setAutoscrolls(true);
        pediddosBttn.setBorder(null);
        pediddosBttn.setBorderPainted(false);
        pediddosBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pediddosBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        pediddosBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        pediddosBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        pediddosBttn.addActionListener(this::pediddosBttnActionPerformed);

        Desktop.setLayer(cardapioBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(estoqueBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(relatoriosBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(caixaBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(sairBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(pediddosBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
            .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DesktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DesktopLayout.createSequentialGroup()
                            .addComponent(cardapioBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(pediddosBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(DesktopLayout.createSequentialGroup()
                            .addComponent(estoqueBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(caixaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(DesktopLayout.createSequentialGroup()
                            .addComponent(relatoriosBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(sairBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
            .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DesktopLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cardapioBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pediddosBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(estoqueBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caixaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(relatoriosBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sairBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardapioBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioBttnActionPerformed
        //arrumar amanha
        CardapioFrame cFrame = new CardapioFrame(cardapiocontroller);
        verificaJanela(cFrame);
    }//GEN-LAST:event_cardapioBttnActionPerformed

    private void pediddosBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediddosBttnActionPerformed
        MenuPedidos telaMenu = new MenuPedidos(pedidoscontroller,Desktop);
        verificaJanela(telaMenu);
    }//GEN-LAST:event_pediddosBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MenuPrincipall().setVisible(true));
    }

    private void verificaJanela(JInternalFrame novoFrame){
        JInternalFrame[] frames = Desktop.getAllFrames();

        for (JInternalFrame frame : frames) {
            frame.dispose();
        }


        novoFrame.setBorder(null);

        ((javax.swing.plaf.basic.BasicInternalFrameUI)novoFrame.getUI()).setNorthPane(null);


        Desktop.add(novoFrame);

        try {
            // 3. FAZ O FRAME PREENCHER TODO O DESKTOP PANE
            novoFrame.setMaximum(true);

            // 4. Remove as bordas e o título (opcional)
            // Use isso se quiser que ele pareça uma "tela fixa" e não uma janela

        } catch (java.beans.PropertyVetoException e) {
            logger.severe(() -> "Erro ao maximizar: " + e.getMessage());
        }
        Desktop.revalidate();
        Desktop.repaint();

        // Mostra frame
        novoFrame.setVisible(true);
    }

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JToggleButton caixaBttn;
    private javax.swing.JToggleButton cardapioBttn;
    private javax.swing.JToggleButton estoqueBttn;
    private javax.swing.JToggleButton pediddosBttn;
    private javax.swing.JToggleButton relatoriosBttn;
    private javax.swing.JToggleButton sairBttn;
    // End of variables declaration//GEN-END:variables
}
