/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.Gregorys2s.view.inicializacao;

import com.github.Gregorys2s.controller.CardapioController;
import com.github.Gregorys2s.entity.Cardapio;
import com.github.Gregorys2s.view.pedidos.CardItem;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Gregory
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());
    private CardapioController cardapioController;
    /**
     * Creates new form MenuInicial
     */
    public MenuInicial(CardapioController cardapioController) {
        this.cardapioController = cardapioController;

        initComponents();

//        telaProdutos.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
//        jScrollPane1.setViewportView(telaProdutos);
        carregarProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        BottonPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelConteudo = new javax.swing.JPanel();
        telaPedidosEmProcesso = new javax.swing.JPanel();
        telaEstoque = new javax.swing.JPanel();
        telaPedidos = new javax.swing.JPanel();
        panelShawarmans = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        imgSha = new javax.swing.JLabel();
        bebidasText = new javax.swing.JLabel();
        quantidadeDeItenBebi = new javax.swing.JLabel();
        panelHamburguer = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenHam = new javax.swing.JLabel();
        hamburguerText = new javax.swing.JLabel();
        imgHambur = new javax.swing.JLabel();
        panelCombos = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenCom = new javax.swing.JLabel();
        combosText = new javax.swing.JLabel();
        imgCombos = new javax.swing.JLabel();
        panelProcoes = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenporcao = new javax.swing.JLabel();
        PorcoesText = new javax.swing.JLabel();
        imgPorcoes = new javax.swing.JLabel();
        panelAlcoolicas = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenAlcool = new javax.swing.JLabel();
        alcoolicasText = new javax.swing.JLabel();
        imgAlcoolicas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MenuBusqueda = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        jTextField1 = new javax.swing.JTextField();
        PedidoText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        telaProdutos = new javax.swing.JPanel();
        SomaDeValores = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        adicionaisText = new javax.swing.JLabel();
        subTotalText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        praViagemPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        btnParaViagem = new javax.swing.JLabel();
        noLocalPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        btnNoLocal = new javax.swing.JLabel();
        RealizarPedidoPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        realizarPedidotext = new javax.swing.JLabel();
        adicionaisText1 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        valorAdicionais = new javax.swing.JLabel();
        valorSubTotal = new javax.swing.JLabel();
        panelItensPedido = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        panelAdicionais = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        combosText1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 43, 43));

        panelMenu.setBackground(new java.awt.Color(33, 33, 33));

        BottonPedidos.setBackground(new java.awt.Color(33, 33, 33));
        BottonPedidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BottonPedidos.setForeground(new java.awt.Color(153, 153, 153));
        BottonPedidos.setText("Pedidos");
        BottonPedidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BottonPedidos.setBorderPainted(false);
        BottonPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BottonPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottonPedidos.setVerifyInputWhenFocusTarget(false);
        BottonPedidos.addActionListener(this::BottonPedidosActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Lanchonete");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BottonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BottonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout telaPedidosEmProcessoLayout = new javax.swing.GroupLayout(telaPedidosEmProcesso);
        telaPedidosEmProcesso.setLayout(telaPedidosEmProcessoLayout);
        telaPedidosEmProcessoLayout.setHorizontalGroup(
            telaPedidosEmProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        telaPedidosEmProcessoLayout.setVerticalGroup(
            telaPedidosEmProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        panelConteudo.add(telaPedidosEmProcesso, "card4");

        javax.swing.GroupLayout telaEstoqueLayout = new javax.swing.GroupLayout(telaEstoque);
        telaEstoque.setLayout(telaEstoqueLayout);
        telaEstoqueLayout.setHorizontalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        telaEstoqueLayout.setVerticalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        panelConteudo.add(telaEstoque, "card3");

        telaPedidos.setBackground(new java.awt.Color(43, 43, 43));

        panelShawarmans.setBackground(java.awt.SystemColor.activeCaption);
        panelShawarmans.setMaximumSize(new java.awt.Dimension(166, 122));

        imgSha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedidos/Refrigerante.png"))); // NOI18N

        bebidasText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bebidasText.setText("Bebidas");

        quantidadeDeItenBebi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantidadeDeItenBebi.setText("?  itens");

        javax.swing.GroupLayout panelShawarmansLayout = new javax.swing.GroupLayout(panelShawarmans);
        panelShawarmans.setLayout(panelShawarmansLayout);
        panelShawarmansLayout.setHorizontalGroup(
            panelShawarmansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShawarmansLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShawarmansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgSha)
                    .addComponent(bebidasText)
                    .addComponent(quantidadeDeItenBebi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelShawarmansLayout.setVerticalGroup(
            panelShawarmansLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShawarmansLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgSha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bebidasText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(quantidadeDeItenBebi)
                .addContainerGap())
        );

        panelHamburguer.setBackground(java.awt.SystemColor.activeCaption);
        panelHamburguer.setMaximumSize(new java.awt.Dimension(166, 1212));
        panelHamburguer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelHamburguerMouseClicked(evt);
            }
        });

        quantidadeDeItenHam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantidadeDeItenHam.setText("?  itens");

        hamburguerText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hamburguerText.setText("Hamburguer");

        imgHambur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedidos/hambur.png"))); // NOI18N

        javax.swing.GroupLayout panelHamburguerLayout = new javax.swing.GroupLayout(panelHamburguer);
        panelHamburguer.setLayout(panelHamburguerLayout);
        panelHamburguerLayout.setHorizontalGroup(
            panelHamburguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHamburguerLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelHamburguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHamburguerLayout.createSequentialGroup()
                        .addGroup(panelHamburguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgHambur)
                            .addComponent(quantidadeDeItenHam, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHamburguerLayout.createSequentialGroup()
                        .addComponent(hamburguerText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelHamburguerLayout.setVerticalGroup(
            panelHamburguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHamburguerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgHambur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(hamburguerText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantidadeDeItenHam, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelCombos.setBackground(java.awt.SystemColor.activeCaption);
        panelCombos.setMaximumSize(new java.awt.Dimension(166, 122));

        quantidadeDeItenCom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantidadeDeItenCom.setText("?  itens");

        combosText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        combosText.setText("Combos");

        imgCombos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedidos/hambur.png"))); // NOI18N

        javax.swing.GroupLayout panelCombosLayout = new javax.swing.GroupLayout(panelCombos);
        panelCombos.setLayout(panelCombosLayout);
        panelCombosLayout.setHorizontalGroup(
            panelCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCombosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combosText)
                    .addComponent(imgCombos)
                    .addComponent(quantidadeDeItenCom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelCombosLayout.setVerticalGroup(
            panelCombosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCombosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combosText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeDeItenCom))
        );

        panelProcoes.setBackground(java.awt.SystemColor.activeCaption);
        panelProcoes.setMaximumSize(new java.awt.Dimension(166, 122));

        quantidadeDeItenporcao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantidadeDeItenporcao.setText("?  itens");

        PorcoesText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PorcoesText.setText("Porções");

        imgPorcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedidos/hambur.png"))); // NOI18N

        javax.swing.GroupLayout panelProcoesLayout = new javax.swing.GroupLayout(panelProcoes);
        panelProcoes.setLayout(panelProcoesLayout);
        panelProcoesLayout.setHorizontalGroup(
            panelProcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcoesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelProcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgPorcoes)
                    .addComponent(PorcoesText)
                    .addComponent(quantidadeDeItenporcao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProcoesLayout.setVerticalGroup(
            panelProcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgPorcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PorcoesText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeDeItenporcao)
                .addContainerGap())
        );

        panelAlcoolicas.setBackground(java.awt.SystemColor.activeCaption);
        panelAlcoolicas.setMaximumSize(new java.awt.Dimension(166, 122));

        quantidadeDeItenAlcool.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quantidadeDeItenAlcool.setText("?  itens");

        alcoolicasText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alcoolicasText.setText("Alcoolicas ");

        imgAlcoolicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedidos/hambur.png"))); // NOI18N

        javax.swing.GroupLayout panelAlcoolicasLayout = new javax.swing.GroupLayout(panelAlcoolicas);
        panelAlcoolicas.setLayout(panelAlcoolicasLayout);
        panelAlcoolicasLayout.setHorizontalGroup(
            panelAlcoolicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlcoolicasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelAlcoolicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgAlcoolicas)
                    .addComponent(quantidadeDeItenAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alcoolicasText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlcoolicasLayout.setVerticalGroup(
            panelAlcoolicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlcoolicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgAlcoolicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alcoolicasText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeDeItenAlcool)
                .addContainerGap())
        );

        MenuBusqueda.setBackground(new java.awt.Color(51, 51, 51));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(242, 242, 242));
        jTextField1.setText("  Procurar");
        jTextField1.setActionCommand(null);
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        javax.swing.GroupLayout MenuBusquedaLayout = new javax.swing.GroupLayout(MenuBusqueda);
        MenuBusqueda.setLayout(MenuBusquedaLayout);
        MenuBusquedaLayout.setHorizontalGroup(
            MenuBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MenuBusquedaLayout.setVerticalGroup(
            MenuBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PedidoText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PedidoText.setForeground(new java.awt.Color(255, 51, 51));
        PedidoText.setText("Pedido #?");

        jScrollPane1.setViewportView(telaProdutos);

        SomaDeValores.setBackground(new java.awt.Color(255, 153, 153));

        adicionaisText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adicionaisText.setText("Adicionais");

        subTotalText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subTotalText.setText("Subtotal");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        btnParaViagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnParaViagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnParaViagem.setText("Para Viagem");

        javax.swing.GroupLayout praViagemPanelLayout = new javax.swing.GroupLayout(praViagemPanel);
        praViagemPanel.setLayout(praViagemPanelLayout);
        praViagemPanelLayout.setHorizontalGroup(
            praViagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(praViagemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnParaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        praViagemPanelLayout.setVerticalGroup(
            praViagemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, praViagemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnParaViagem, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNoLocal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNoLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNoLocal.setText("No Local");
        btnNoLocal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout noLocalPanelLayout = new javax.swing.GroupLayout(noLocalPanel);
        noLocalPanel.setLayout(noLocalPanelLayout);
        noLocalPanelLayout.setHorizontalGroup(
            noLocalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noLocalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        noLocalPanelLayout.setVerticalGroup(
            noLocalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noLocalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNoLocal.getAccessibleContext().setAccessibleDescription("");

        realizarPedidotext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        realizarPedidotext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        realizarPedidotext.setText("Realizar Pedido");

        javax.swing.GroupLayout RealizarPedidoPanelLayout = new javax.swing.GroupLayout(RealizarPedidoPanel);
        RealizarPedidoPanel.setLayout(RealizarPedidoPanelLayout);
        RealizarPedidoPanelLayout.setHorizontalGroup(
            RealizarPedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealizarPedidoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realizarPedidotext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RealizarPedidoPanelLayout.setVerticalGroup(
            RealizarPedidoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RealizarPedidoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realizarPedidotext, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        adicionaisText1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adicionaisText1.setText("Total");

        valorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorTotal.setText("R$    ???");

        valorAdicionais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorAdicionais.setText("R$    ???");

        valorSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorSubTotal.setText("R$    ???");

        javax.swing.GroupLayout SomaDeValoresLayout = new javax.swing.GroupLayout(SomaDeValores);
        SomaDeValores.setLayout(SomaDeValoresLayout);
        SomaDeValoresLayout.setHorizontalGroup(
            SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SomaDeValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SomaDeValoresLayout.createSequentialGroup()
                        .addComponent(praViagemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noLocalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RealizarPedidoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SomaDeValoresLayout.createSequentialGroup()
                        .addComponent(subTotalText)
                        .addGap(161, 161, 161)
                        .addComponent(valorSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SomaDeValoresLayout.createSequentialGroup()
                        .addComponent(adicionaisText1)
                        .addGap(189, 189, 189)
                        .addComponent(valorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SomaDeValoresLayout.createSequentialGroup()
                        .addComponent(adicionaisText)
                        .addGap(145, 145, 145)
                        .addComponent(valorAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SomaDeValoresLayout.setVerticalGroup(
            SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SomaDeValoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalText)
                    .addComponent(valorSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionaisText)
                    .addComponent(valorAdicionais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionaisText1)
                    .addComponent(valorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(SomaDeValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(praViagemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noLocalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(RealizarPedidoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelItensPedidoLayout = new javax.swing.GroupLayout(panelItensPedido);
        panelItensPedido.setLayout(panelItensPedidoLayout);
        panelItensPedidoLayout.setHorizontalGroup(
            panelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelItensPedidoLayout.setVerticalGroup(
            panelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        panelAdicionais.setBackground(java.awt.SystemColor.activeCaption);
        panelAdicionais.setMaximumSize(new java.awt.Dimension(166, 122));

        combosText1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        combosText1.setText("Adicionais");

        javax.swing.GroupLayout panelAdicionaisLayout = new javax.swing.GroupLayout(panelAdicionais);
        panelAdicionais.setLayout(panelAdicionaisLayout);
        panelAdicionaisLayout.setHorizontalGroup(
            panelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combosText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAdicionaisLayout.setVerticalGroup(
            panelAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combosText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout telaPedidosLayout = new javax.swing.GroupLayout(telaPedidos);
        telaPedidos.setLayout(telaPedidosLayout);
        telaPedidosLayout.setHorizontalGroup(
            telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaPedidosLayout.createSequentialGroup()
                        .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(telaPedidosLayout.createSequentialGroup()
                                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelAlcoolicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelHamburguer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelProcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelShawarmans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(telaPedidosLayout.createSequentialGroup()
                        .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator1))
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PedidoText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SomaDeValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelItensPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        telaPedidosLayout.setVerticalGroup(
            telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaPedidosLayout.createSequentialGroup()
                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaPedidosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MenuBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaPedidosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PedidoText)
                        .addGap(18, 18, 18)))
                .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaPedidosLayout.createSequentialGroup()
                        .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelShawarmans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelHamburguer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAlcoolicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelProcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaPedidosLayout.createSequentialGroup()
                        .addComponent(panelItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SomaDeValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConteudo.add(telaPedidos, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonPedidosActionPerformed
        CardLayout cl = (CardLayout) panelConteudo.getLayout();
        cl.show(panelConteudo, "card2");
    }//GEN-LAST:event_BottonPedidosActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void panelHamburguerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHamburguerMouseClicked
        // quando clickar o panel deve mostrar os produtos da secao que foi clicada
    }//GEN-LAST:event_panelHamburguerMouseClicked

    private JPanel criarCard(String nome, BigDecimal preco) {

        return new CardItem(nome,preco);

    }

    private void carregarProdutos() {

        telaProdutos.removeAll();
        List<Cardapio> produtos = cardapioController.obterLista();

        for(Cardapio item : produtos){
            telaProdutos.add(criarCard(item.getNome(),item.getPreco()));
        }

        telaProdutos.revalidate();
        telaProdutos.repaint();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottonPedidos;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo MenuBusqueda;
    private javax.swing.JLabel PedidoText;
    private javax.swing.JLabel PorcoesText;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo RealizarPedidoPanel;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo SomaDeValores;
    private javax.swing.JLabel adicionaisText;
    private javax.swing.JLabel adicionaisText1;
    private javax.swing.JLabel alcoolicasText;
    private javax.swing.JLabel bebidasText;
    private javax.swing.JLabel btnNoLocal;
    private javax.swing.JLabel btnParaViagem;
    private javax.swing.JLabel combosText;
    private javax.swing.JLabel combosText1;
    private javax.swing.JLabel hamburguerText;
    private javax.swing.JLabel imgAlcoolicas;
    private javax.swing.JLabel imgCombos;
    private javax.swing.JLabel imgHambur;
    private javax.swing.JLabel imgPorcoes;
    private javax.swing.JLabel imgSha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo noLocalPanel;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelAdicionais;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelAlcoolicas;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelCombos;
    private javax.swing.JPanel panelConteudo;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelHamburguer;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelItensPedido;
    private javax.swing.JPanel panelMenu;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelProcoes;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelShawarmans;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo praViagemPanel;
    private javax.swing.JLabel quantidadeDeItenAlcool;
    private javax.swing.JLabel quantidadeDeItenBebi;
    private javax.swing.JLabel quantidadeDeItenCom;
    private javax.swing.JLabel quantidadeDeItenHam;
    private javax.swing.JLabel quantidadeDeItenporcao;
    private javax.swing.JLabel realizarPedidotext;
    private javax.swing.JLabel subTotalText;
    private javax.swing.JPanel telaEstoque;
    private javax.swing.JPanel telaPedidos;
    private javax.swing.JPanel telaPedidosEmProcesso;
    private javax.swing.JPanel telaProdutos;
    private javax.swing.JLabel valorAdicionais;
    private javax.swing.JLabel valorSubTotal;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
