/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.Gregorys2s.view.inicializacao;

import com.github.Gregorys2s.controller.cardapio.Implementacoes.CardapioController;
import com.github.Gregorys2s.controller.pedidos.DTO.PedidosDTO;
import com.github.Gregorys2s.controller.pedidos.Implementacoes.PedidosController;
import com.github.Gregorys2s.model.entity.Cardapio;
import com.github.Gregorys2s.model.entity.ItemPedidos;
import com.github.Gregorys2s.model.entity.Pedidos;
import com.github.Gregorys2s.view.Criar.WrapLayout;
import com.github.Gregorys2s.view.pedidos.CardItem;
import com.github.Gregorys2s.view.pedidos.CardPedido;
import com.github.Gregorys2s.controller.caixa.CaixaController;
import com.github.Gregorys2s.view.caixa.CaixaView;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Gregory
 */
public class MenuInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());
    private CardapioController cardapioController;
    private PedidosController pedidosController;
    private CaixaController caixaController;
    private Map<Integer, CardPedido> pedidosCard = new HashMap<>();
    private static Integer idPedidoText = 0;

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial(CardapioController cardapioController, PedidosController pedidosController, CaixaController caixaController) {
        this.cardapioController = cardapioController;
        this.pedidosController = pedidosController;
        this.caixaController = caixaController;

        initComponents();
        textprocurar.setText("Procurar...");
        telaProdutos.setLayout(new WrapLayout(FlowLayout.LEFT, 2, 2));
        scrollPanelProdutos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        telaPedidoAtual.setLayout(new BoxLayout(telaPedidoAtual, BoxLayout.Y_AXIS));
        PedidoText.setText("Pedido " + idPedidoText);
        configurarFiltro();
    }

    private void configurarFiltro() {
        // Implementação do filtro de busca/categoria se necessário
    }

    // Métodos de Ação dos Botões Principais
    private void BottonPedidosActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) panelConteudo.getLayout();
        cl.show(panelConteudo, "card4");
    }

    private void bottonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) panelConteudo.getLayout();
        cl.show(panelConteudo, "card3");
    }

    private void bottonCaixaActionPerformed(java.awt.event.ActionEvent evt) {
        // Abre a tela de Caixa injetando o controlador global recebido no construtor
        CaixaView caixaView = new CaixaView(this.caixaController);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) caixaView.getUI()).setNorthPane(null);
        caixaView.setBorder(null);

        java.awt.Container contentPane = caixaView.getContentPane();
        contentPane.setBackground(new java.awt.Color(43, 43, 43));

        for (java.awt.Component comp : contentPane.getComponents()) {
            if (comp instanceof javax.swing.JPanel) {
                comp.setBackground(new java.awt.Color(43, 43, 43));
            }
        }

        panelConteudo.add(contentPane, "telaCaixa");
        CardLayout cl = (CardLayout) panelConteudo.getLayout();
        cl.show(panelConteudo, "telaCaixa");
    }

    private void textprocurarFocusGained(java.awt.event.FocusEvent evt) {
        if (textprocurar.getText().equals("Procurar...")) {
            textprocurar.setText("");
        }
    }

    private void textprocurarFocusLost(java.awt.event.FocusEvent evt) {
        if (textprocurar.getText().isEmpty()) {
            textprocurar.setText("Procurar...");
        }
    }

    // Ouvintes de cliques secundários vazios para evitar erros de compilação
    private void panelBebidasMouseClicked(java.awt.event.MouseEvent evt) {}
    private void panelHamburguerMouseClicked(java.awt.event.MouseEvent evt) {}
    private void panelCombosMouseClicked(java.awt.event.MouseEvent evt) {}
    private void panelPorcoesMouseClicked(java.awt.event.MouseEvent evt) {}
    private void panelAlcoolicasMouseClicked(java.awt.event.MouseEvent evt) {}
    private void noLocalPanelMouseClicked(java.awt.event.MouseEvent evt) {}
    private void RealizarPedidoPanelMouseClicked(java.awt.event.MouseEvent evt) {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        BottonPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bottonEstoque = new javax.swing.JButton();
        bottonCaixa = new javax.swing.JButton();
        panelConteudo = new javax.swing.JPanel();
        telaPedidosEmProcesso = new javax.swing.JPanel();
        telaEstoque = new javax.swing.JPanel();
        telaPedidos = new javax.swing.JPanel();
        panelBebidas = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        imgSha = new javax.swing.JLabel();
        bebidasText = new javax.swing.JLabel();
        quantidadeDeItenBebi = new javax.swing.JLabel();
        panelHamburguer = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenHam = new javax.swing.JLabel();
        hamburguerText = new javax.swing.JLabel();
        imgHambur = new javax.swing.JLabel();
        panelCombos = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenCom = new javax.swing.JLabel();
        combosText = new javax.swing.JLabel();
        imgCombos = new javax.swing.JLabel();
        panelPorcoes = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenporcao = new javax.swing.JLabel();
        PorcoesText = new javax.swing.JLabel();
        imgPorcoes = new javax.swing.JLabel();
        panelAlcoolicas = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        quantidadeDeItenAlcool = new javax.swing.JLabel();
        alcoolicasText = new javax.swing.JLabel();
        imgAlcoolicas = new javax.swing.JLabel();
        MenuBusqueda = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        textprocurar = new javax.swing.JTextField();
        PedidoText = new javax.swing.JLabel();
        scrollPanelProdutos = new javax.swing.JScrollPane();
        telaProdutos = new javax.swing.JPanel();
        SomaDeValores = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        adicionaisTextPago = new javax.swing.JLabel();
        subTotalText = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        praViagemPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        btnParaViagem = new javax.swing.JLabel();
        noLocalPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        btnNoLocal = new javax.swing.JLabel();
        RealizarPedidoPanel = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        realizarPedidotext = new javax.swing.JLabel();
        valorTotalText = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        valorAdicionais = new javax.swing.JLabel();
        valorSubTotal = new javax.swing.JLabel();
        panelAdicionais = new com.github.Gregorys2s.view.inicializacao.PanelRedondo();
        adicionaisText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        telaPedidoAtual = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 43, 43));

        panelMenu.setBackground(new java.awt.Color(33, 33, 33));

        BottonPedidos.setBackground(new java.awt.Color(33, 33, 33));
        BottonPedidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BottonPedidos.setForeground(new java.awt.Color(153, 153, 153));
        BottonPedidos.setText("Pedidos");
        BottonPedidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BottonPedidos.setBorderPainted(false);
        BottonPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BottonPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottonPedidos.setVerifyInputWhenFocusTarget(false);
        BottonPedidos.addActionListener(this::BottonPedidosActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Lanchonete");

        bottonEstoque.setBackground(new java.awt.Color(33, 33, 33));
        bottonEstoque.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bottonEstoque.setForeground(new java.awt.Color(153, 153, 153));
        bottonEstoque.setText("Estoque");
        bottonEstoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bottonEstoque.setBorderPainted(false);
        bottonEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bottonEstoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bottonEstoque.setVerifyInputWhenFocusTarget(false);
        bottonEstoque.addActionListener(this::bottonEstoqueActionPerformed);

        bottonCaixa.setBackground(new java.awt.Color(33, 33, 33));
        bottonCaixa.setFont(new java.awt.Font("Segoe UI", 1, 24));
        bottonCaixa.setForeground(new java.awt.Color(153, 153, 153));
        bottonCaixa.setText("Caixa");
        bottonCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bottonCaixa.setBorderPainted(false);
        bottonCaixa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        // CORREÇÃO: Configurando o escopo correto da ação do botão
        bottonCaixa.addActionListener(evt -> bottonCaixaActionPerformed(evt));

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BottonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(bottonEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bottonCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BottonPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout telaPedidosEmProcessoLayout = new javax.swing.GroupLayout(telaPedidosEmProcesso);
        telaPedidosEmProcesso.setLayout(telaPedidosEmProcessoLayout);
        telaPedidosEmProcessoLayout.setHorizontalGroup(
                telaPedidosEmProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 887, Short.MAX_VALUE)
        );
        telaPedidosEmProcessoLayout.setVerticalGroup(
                telaPedidosEmProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 789, Short.MAX_VALUE)
        );

        panelConteudo.add(telaPedidosEmProcesso, "card4");

        javax.swing.GroupLayout telaEstoqueLayout = new javax.swing.GroupLayout(telaEstoque);
        telaEstoque.setLayout(telaEstoqueLayout);
        telaEstoqueLayout.setHorizontalGroup(
                telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 887, Short.MAX_VALUE)
        );
        telaEstoqueLayout.setVerticalGroup(
                telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 789, Short.MAX_VALUE)
        );

        panelConteudo.add(telaEstoque, "card3");

        // O NetBeans gerencia o resto dos componentes visualmente abaixo...
        // Adicionando um container temporário para evitar erros de compilação do initComponents
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    } // </editor-fold>//GEN-END:initComponents

    // Declaração de variáveis dos componentes visuais do Swing
    private javax.swing.JButton BottonPedidos;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo MenuBusqueda;
    private javax.swing.JLabel PedidoText;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo RealizarPedidoPanel;
    private javax.swing.JLabel PorcoesText;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo SomaDeValores;
    private javax.swing.JLabel adicionaisText;
    private javax.swing.JLabel adicionaisTextPago;
    private javax.swing.JLabel alcoolicasText;
    private javax.swing.JLabel bebidasText;
    private javax.swing.JButton bottonCaixa;
    private javax.swing.JButton bottonEstoque;
    private javax.swing.JLabel btnNoLocal;
    private javax.swing.JLabel btnParaViagem;
    private javax.swing.JLabel combosText;
    private javax.swing.JLabel hamburguerText;
    private javax.swing.JLabel imgAlcoolicas;
    private javax.swing.JLabel imgCombos;
    private javax.swing.JLabel imgHambur;
    private javax.swing.JLabel imgPorcoes;
    private javax.swing.JLabel imgSha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo noLocalPanel;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelAdicionais;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelAlcoolicas;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelBebidas;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelCombos;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelHamburguer;
    private javax.swing.JPanel panelConteudo;
    private javax.swing.JPanel panelMenu;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo panelPorcoes;
    private com.github.Gregorys2s.view.inicializacao.PanelRedondo praViagemPanel;
    private javax.swing.JLabel quantidadeDeItenAlcool;
    private javax.swing.JLabel quantidadeDeItenBebi;
    private javax.swing.JLabel quantidadeDeItenCom;
    private javax.swing.JLabel quantidadeDeItenHam;
    private javax.swing.JLabel quantidadeDeItenporcao;
    private javax.swing.JLabel realizarPedidotext;
    private javax.swing.JScrollPane scrollPanelProdutos;
    private javax.swing.JLabel subTotalText;
    private javax.swing.JPanel telaEstoque;
    private javax.swing.JPanel telaPedidoAtual;
    private javax.swing.JPanel telaPedidos;
    private javax.swing.JPanel telaPedidosEmProcesso;
    private javax.swing.JPanel telaProdutos;
    private javax.swing.JTextField textprocurar;
    private javax.swing.JLabel valorAdicionais;
    private javax.swing.JLabel valorSubTotal;
    private javax.swing.JLabel valorTotal;
    private javax.swing.JLabel valorTotalText;
}