/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.Gregorys2s.view.inicializacao;

import com.github.Gregorys2s.controller.CardapioController;
import com.github.Gregorys2s.repositories.CardapioRepository;
import com.github.Gregorys2s.service.CardapioService;
import com.github.Gregorys2s.view.cardapio.CardapioFrame;
import com.github.Gregorys2s.view.cardapio.CardapioView;
import com.github.Gregorys2s.view.pedidos.MenuPedidos;
import jakarta.persistence.EntityManager;
import java.awt.Desktop;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;


/**
 *
 * @author pedro
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(MenuPrincipal.class.getName());
    private final EntityManager em;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(EntityManager em) {
//        setTitle("MENU PRINCIPAL");
//        setSize(400, 300);
//        setLayout(new BorderLayout(10,10));
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setLocationRelativeTo(null);
//        JLabel titulo = new JLabel("Menu principal", SwingUtilities.CENTER);

        this.em = em;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        cardapioBttn = new javax.swing.JToggleButton();
        estoqueBttn = new javax.swing.JToggleButton();
        relatoriosBttn = new javax.swing.JToggleButton();
        caixaBttn = new javax.swing.JToggleButton();
        sairBttn = new javax.swing.JToggleButton();
        pediddosBttn = new javax.swing.JToggleButton();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        cardapioBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cardapioBttn.setText("Cardapio");
        cardapioBttn.setToolTipText("");
        cardapioBttn.setAutoscrolls(true);
        cardapioBttn.setBorder(null);
        cardapioBttn.setBorderPainted(false);
        cardapioBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cardapioBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        cardapioBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        cardapioBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        cardapioBttn.addActionListener(this::cardapioBttnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(cardapioBttn, gridBagConstraints);
        cardapioBttn.getAccessibleContext().setAccessibleDescription("");

        estoqueBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        estoqueBttn.setText("Estoque");
        estoqueBttn.setToolTipText("");
        estoqueBttn.setAutoscrolls(true);
        estoqueBttn.setBorder(null);
        estoqueBttn.setBorderPainted(false);
        estoqueBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estoqueBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        estoqueBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        estoqueBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(estoqueBttn, gridBagConstraints);
        estoqueBttn.getAccessibleContext().setAccessibleDescription("");

        relatoriosBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        relatoriosBttn.setText("Relatorios");
        relatoriosBttn.setToolTipText("");
        relatoriosBttn.setAutoscrolls(true);
        relatoriosBttn.setBorder(null);
        relatoriosBttn.setBorderPainted(false);
        relatoriosBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        relatoriosBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        relatoriosBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        relatoriosBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(relatoriosBttn, gridBagConstraints);
        relatoriosBttn.getAccessibleContext().setAccessibleDescription("");

        caixaBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caixaBttn.setText("Caixa");
        caixaBttn.setToolTipText("");
        caixaBttn.setAutoscrolls(true);
        caixaBttn.setBorder(null);
        caixaBttn.setBorderPainted(false);
        caixaBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        caixaBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        caixaBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        caixaBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(caixaBttn, gridBagConstraints);
        caixaBttn.getAccessibleContext().setAccessibleDescription("");

        sairBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sairBttn.setText("Sair");
        sairBttn.setToolTipText("");
        sairBttn.setAutoscrolls(true);
        sairBttn.setBorder(null);
        sairBttn.setBorderPainted(false);
        sairBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sairBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        sairBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        sairBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(sairBttn, gridBagConstraints);
        sairBttn.getAccessibleContext().setAccessibleDescription("");

        pediddosBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pediddosBttn.setText("Pedidos");
        pediddosBttn.setToolTipText("");
        pediddosBttn.setAutoscrolls(true);
        pediddosBttn.setBorder(null);
        pediddosBttn.setBorderPainted(false);
        pediddosBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pediddosBttn.setMaximumSize(new java.awt.Dimension(500, 500));
        pediddosBttn.setMinimumSize(new java.awt.Dimension(200, 50));
        pediddosBttn.setPreferredSize(new java.awt.Dimension(200, 50));
        pediddosBttn.addActionListener(this::pediddosBttnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 5);
        jPanel1.add(pediddosBttn, gridBagConstraints);
        pediddosBttn.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        desktopPane.setVerifyInputWhenFocusTarget(false);
        desktopPane.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(desktopPane, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardapioBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioBttnActionPerformed
        CardapioRepository cardapioRepository = new CardapioRepository(em);
        CardapioService cardapioService = new CardapioService(cardapioRepository);
        CardapioController cardapioController = new CardapioController(cardapioService);
        //arrumar amanha
        CardapioFrame cFrame = new CardapioFrame(cardapioController);
        verificaJanela(cFrame);
    }//GEN-LAST:event_cardapioBttnActionPerformed

    private void pediddosBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediddosBttnActionPerformed
        MenuPedidos telaMenu = new MenuPedidos(desktopPane);
        verificaJanela(telaMenu);
    }//GEN-LAST:event_pediddosBttnActionPerformed
    private void verificaJanela(JInternalFrame novoFrame){
        JInternalFrame[] frames = desktopPane.getAllFrames();

        for (javax.swing.JInternalFrame frame : frames) {
            frame.dispose();
        }

        desktopPane.add(novoFrame);
        novoFrame.setVisible(true);

        try {
        // 3. FAZ O FRAME PREENCHER TODO O DESKTOP PANE
        novoFrame.setMaximum(true); 
        
        // 4. Remove as bordas e o título (opcional) 
        // Use isso se quiser que ele pareça uma "tela fixa" e não uma janela
        novoFrame.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI)novoFrame.getUI()).setNorthPane(null);
        
        } catch (java.beans.PropertyVetoException e) {
            logger.severe(() -> "Erro ao maximizar: " + e.getMessage());
        }
        novoFrame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton caixaBttn;
    private javax.swing.JToggleButton cardapioBttn;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JToggleButton estoqueBttn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton pediddosBttn;
    private javax.swing.JToggleButton relatoriosBttn;
    private javax.swing.JToggleButton sairBttn;
    // End of variables declaration//GEN-END:variables
}
