/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.pedidos;

import com.github.Gregorys2s.controller.pedidos.Implementacoes.PedidosController;
import com.github.Gregorys2s.controller.pedidos.DTO.PedidosDTO;
import com.github.Gregorys2s.model.entity.ItemPedidos;
import com.github.Gregorys2s.util.LeitoresSwing;
import com.github.Gregorys2s.view.Pagamentos.PagamentoView;
import com.github.Gregorys2s.view.tema.TemaSistema;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Gregory
 */
public class PedidosEmProcesso extends javax.swing.JInternalFrame {

    private PedidosController pedidos;
    private JPanel pedidosContainer;
    private javax.swing.JDesktopPane desktop;

    public PedidosEmProcesso(PedidosController pedidos, JDesktopPane desktop) {
        this.desktop = desktop;
        this.pedidos = pedidos;

        initComponents();
        configurarVisual();
        carregarTabela();
    }

    private void configurarVisual() {
        TemaSistema.aplicar(this);
        
        pedidosContainer = new JPanel();
        pedidosContainer.setLayout(new BoxLayout(pedidosContainer, BoxLayout.Y_AXIS));
        pedidosContainer.setBackground(TemaSistema.fundo());

        jScrollPane1.setViewportView(pedidosContainer);
        jScrollPane1.setBorder(BorderFactory.createLineBorder(TemaSistema.borda()));
        
        // Cores específicas para ações
        FinalizarPedido.setBackground(TemaSistema.sucesso());
        CancelarPedido.setBackground(TemaSistema.perigo());
        VoltarAoMenu1.setBackground(TemaSistema.secundaria());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        CancelarPedido = new javax.swing.JButton();
        FinalizarPedido = new javax.swing.JButton();
        VoltarAoMenu1 = new javax.swing.JButton();

        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N* Pedido", "Itens", "Valor total"
            }
        ));
        jScrollPane1.setViewportView(TabelaPedidos);

        CancelarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CancelarPedido.setText("Cancelar Pedido");
        CancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarPedidoActionPerformed(evt);
            }
        });

        FinalizarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FinalizarPedido.setText("Concluir Pedido");
        FinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarPedidoActionPerformed(evt);
            }
        });

        VoltarAoMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VoltarAoMenu1.setText("Voltar");
        VoltarAoMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarAoMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(FinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VoltarAoMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(VoltarAoMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarAoMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenu1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_VoltarAoMenu1ActionPerformed

    private void FinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarPedidoActionPerformed
        Integer id = LeitoresSwing.lerInteger("Qual é o número do pedido?");
        if (id == null) return;
        
        PedidosDTO pedido = pedidos.procurarPorId(id);

        if (pedido == null) {
            JOptionPane.showMessageDialog(this, "Pedido não encontrado!");
            return;
        }

        PagamentoView pagamentoView = new PagamentoView();
        desktop.add(pagamentoView);
        pagamentoView.setVisible(true);

        pagamentoView.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                        String metodo = pagamentoView.getMetodoPagamento();

                        if (metodo != null){
                            BigDecimal valorPago = LeitoresSwing.lerBigDecimal("Digite o valor pago");

                            if (valorPago == null) return;

                            if (valorPago.compareTo(pedido.getValorTotal()) < 0) {
                                BigDecimal restante = pedido.getValorTotal().subtract(valorPago);
                                JOptionPane.showMessageDialog(
                                        null,
                                        "Erro: Valor insuficiente.\nFalta pagar: R$ " + restante,
                                        "Pagamento Insuficiente",
                                        JOptionPane.ERROR_MESSAGE
                                );
                                return;
                            }

                            pedidos.finalizarPedido(pedido, metodo, valorPago);
                            carregarTabela();
                        }
                    }
                }
        );
    }//GEN-LAST:event_FinalizarPedidoActionPerformed

    private void carregarTabela() {
        pedidosContainer.removeAll();

        List<PedidosDTO> lista = pedidos.procurarPedidos();
        for (PedidosDTO p : lista) {
            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Produto", "Qtd", "Total"}, 0
            );

            for (ItemPedidos item : p.getItens()) {
                model.addRow(new Object[]{
                        item.getProduto().getNome(),
                        item.getQuantidade(),
                        item.getProduto().getPreco().multiply(new BigDecimal(item.getQuantidade()))
                });
            }

            JTable tabela = new JTable(model);
            TemaSistema.estilizarTabela(tabela);

            JPanel painelPedido = new JPanel(new BorderLayout(5, 5));
            painelPedido.setBackground(TemaSistema.card());
            painelPedido.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createTitledBorder(BorderFactory.createLineBorder(TemaSistema.borda()), "Pedido #" + p.getId(), 0, 0, new Font("Segoe UI", Font.BOLD, 14), TemaSistema.primaria()),
                    BorderFactory.createEmptyBorder(5, 5, 5, 5)
            ));

            painelPedido.setPreferredSize(new Dimension(450, 180));
            painelPedido.setMaximumSize(new Dimension(Integer.MAX_VALUE, 180));

            JScrollPane scrollTabela = new JScrollPane(tabela);
            scrollTabela.setBorder(null);
            painelPedido.add(scrollTabela, BorderLayout.CENTER);

            JPanel infoPanel = new JPanel(new GridLayout(2, 1));
            infoPanel.setOpaque(false);

            JLabel adicionalLabel = new JLabel("Adicional: " + (p.getAdicionais() != null ? p.getAdicionais() : "Nenhum"));
            adicionalLabel.setForeground(TemaSistema.textoSecundario());
            
            JLabel adicionalTotal = new JLabel("VALOR TOTAL: R$ " + p.getValorTotal());
            adicionalTotal.setFont(new Font("Segoe UI", Font.BOLD, 16));
            adicionalTotal.setForeground(TemaSistema.primaria());
            adicionalTotal.setHorizontalAlignment(SwingConstants.RIGHT);

            infoPanel.add(adicionalLabel);
            infoPanel.add(adicionalTotal);

            painelPedido.add(infoPanel, BorderLayout.SOUTH);

            pedidosContainer.add(painelPedido);
            pedidosContainer.add(Box.createVerticalStrut(10));
        }

        pedidosContainer.revalidate();
        pedidosContainer.repaint();
    }

    private void CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {
        Integer idPedido = LeitoresSwing.lerInteger("Qual o número do pedido que deseja cancelar?");
        if (idPedido == null) return;

        int confirmar = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente cancelar o pedido #" + idPedido + "?",
                "Cancelar Pedido",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmar == JOptionPane.YES_OPTION) {
            pedidos.cancelarPedido(idPedido);
            JOptionPane.showMessageDialog(this, "Pedido cancelado com sucesso!");
            carregarTabela();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarPedido;
    private javax.swing.JButton FinalizarPedido;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JButton VoltarAoMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
