/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.pedidos;

import com.github.Gregorys2s.controller.Leitores;
import com.github.Gregorys2s.controller.PedidosController;
import com.github.Gregorys2s.entity.ItemPedidos;
import com.github.Gregorys2s.entity.Pagamento;
import com.github.Gregorys2s.entity.Pedidos;
import com.github.Gregorys2s.util.LeitoresSwing;
import com.github.Gregorys2s.view.Pagamentos.PagamentoView;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Gregory
 */
public class PedidosEmProcesso extends javax.swing.JInternalFrame {

    PedidosController pedidos;
    private JPanel pedidosContainer;
    private javax.swing.JDesktopPane desktop;

    public PedidosEmProcesso(PedidosController pedidos,JDesktopPane desktop) {
        this.desktop = desktop;
        this.pedidos = pedidos;

        initComponents();

        pedidosContainer = new JPanel();
        pedidosContainer.setLayout(new BoxLayout(pedidosContainer, BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(pedidosContainer);

        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        CancelarPedido = new javax.swing.JButton();
        FinalizarPedido = new javax.swing.JButton();
        VoltarAoMenu1 = new javax.swing.JButton();

        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N* Pedido", "Itens", "Valor total"
            }
        ));
        jScrollPane1.setViewportView(TabelaPedidos);

        CancelarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CancelarPedido.setText("Cancelar Pedido");
        CancelarPedido.addActionListener(this::CancelarPedidoActionPerformed);

        FinalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FinalizarPedido.setText("Concluir Pedido");
        FinalizarPedido.addActionListener(this::FinalizarPedidoActionPerformed);

        VoltarAoMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VoltarAoMenu1.setText("Voltar");
        VoltarAoMenu1.addActionListener(this::VoltarAoMenu1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VoltarAoMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(148, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(VoltarAoMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarAoMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarAoMenu1ActionPerformed
        JOptionPane.showMessageDialog(null,"Voltando ao menu");
        this.dispose();
    }//GEN-LAST:event_VoltarAoMenu1ActionPerformed

    private void FinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarPedidoActionPerformed
        Integer id = LeitoresSwing.lerInteger("Qual e o numero do pedido?");
        Pedidos pedido = pedidos.procurarPorId(id);

        if (pedido == null) {
            JOptionPane.showMessageDialog(null, "Pedido não encontrado!");
            return;
        }

        PagamentoView pagamentoView = new PagamentoView();
        desktop.add(pagamentoView);
        pagamentoView.setVisible(true);

        pagamentoView.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                        String metodo = pagamentoView.getMetodoPagamento();

                        if (metodo != null){
                            BigDecimal valorPago = LeitoresSwing.lerBigDecimal("Digite o valor pago");

                            if (valorPago == null) return;

                            // VALIDAÇÃO: Se valorPago for MENOR que o valor total do pedido
                            if (valorPago.compareTo(pedido.getValorTotal()) < 0) {
                                BigDecimal restante = pedido.getValorTotal().subtract(valorPago);

                                JOptionPane.showMessageDialog(
                                        null,
                                        "Erro: O valor pago (R$ " + valorPago + ") é menor que o valor do pedido (R$ " + pedido.getValorTotal() + ").\n" +
                                                "Falta pagar: R$ " + restante,
                                        "Pagamento Insuficiente",
                                        JOptionPane.ERROR_MESSAGE
                                );
                                return; // Bloqueia a finalização do pedido
                            }

                            // Se o valor for suficiente, finaliza normalmente
                            pedidos.finalizarPedido(pedido, metodo, valorPago);
                            carregarTabela();
                        }
                    }
                }
        );
    }//GEN-LAST:event_FinalizarPedidoActionPerformed

    private void carregarTabela() {

        pedidosContainer.removeAll();

        List<Pedidos> lista = pedidos.procurarPedidos();

        for (Pedidos p : lista) {

            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Produto", "Qtd", "Total"}, 0
            );

            for (ItemPedidos item : p.getItens()) {
                model.addRow(new Object[]{
                        item.getProduto().getNome(),
                        item.getQuantidade(),
                        item.getProduto().getPreco().multiply(new BigDecimal(item.getQuantidade()))
                });
            }

            JTable tabela = new JTable(model);

            JPanel painelPedido = new JPanel(new BorderLayout());
            painelPedido.setBorder(
                    BorderFactory.createTitledBorder("Pedido " + p.getId())
            );



            painelPedido.setPreferredSize(new Dimension(420, 120));
            painelPedido.setMaximumSize(new Dimension(Integer.MAX_VALUE, 120));

            painelPedido.add(new JScrollPane(tabela));

            JLabel adicionalLabel = new JLabel(
                    "Adicional: " + p.getAdicionais()
            );

            JLabel adicionalTotal = new JLabel(
                    "Valor Total: " + p.getValorTotal()
            );

            JPanel infoPanel = new JPanel();
            infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));

            infoPanel.add(adicionalLabel);
            infoPanel.add(adicionalTotal);

            painelPedido.add(
                    infoPanel,
                    BorderLayout.SOUTH
            );

            pedidosContainer.add(painelPedido);
        }

        pedidosContainer.revalidate();
        pedidosContainer.repaint();
    }
            

    private void CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            Integer id = LeitoresSwing.lerInteger("Qual e o numero do pedido?");
            pedidos.cancelarPedido(id);
            JOptionPane.showMessageDialog(null,"Pedido cancelado com sucesso");
            carregarTabela();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Erro");
        }



    }                                              

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarPedido;
    private javax.swing.JButton FinalizarPedido;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JButton VoltarAoMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
