    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.Panel;

import com.github.Gregorys2s.config.AppConfig;
import com.github.Gregorys2s.config.Appteste;

import javax.swing.*;

/**
 *
 * @author Gregory
 */
public class MenuPedidos extends javax.swing.JInternalFrame {
    private final Appteste app = new Appteste();
    private javax.swing.JDesktopPane desktop;

    public MenuPedidos(JDesktopPane desktop) {
        this.desktop = desktop;
        initComponents();
    }

    /**
     * Creates new form Pedido
     */
    public MenuPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        VerPedidos = new javax.swing.JButton();
        FazerPedido = new javax.swing.JButton();
        VoltarMenu = new javax.swing.JButton();
        menu = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setPreferredSize(new java.awt.Dimension(900, 900));

        VerPedidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        VerPedidos.setText("Ver todos os pedidos");
        VerPedidos.addActionListener(this::VerPedidosActionPerformed);

        FazerPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FazerPedido.setText("Realizar pedido");
        FazerPedido.addActionListener(this::FazerPedidoActionPerformed);

        VoltarMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        VoltarMenu.setText("Voltar ao menu");
        VoltarMenu.addActionListener(this::VoltarMenuActionPerformed);

        menu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VoltarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FazerPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VoltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerPedidosActionPerformed

    private void FazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerPedidoActionPerformed
        pedidosView pedido = new Appteste.AppConfig().criarPedidosView();
        desktop.add(pedido);
        pedido.setVisible(true);
        
        
    }//GEN-LAST:event_FazerPedidoActionPerformed

    private void VoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FazerPedido;
    private javax.swing.JButton VerPedidos;
    private javax.swing.JButton VoltarMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
