/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.Panel;

import com.github.Gregorys2s.controller.PedidosController;
import com.github.Gregorys2s.entity.ItemPedidos;
import com.github.Gregorys2s.entity.Pedidos;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Gregory
 */
public class PedidosEmProcesso extends javax.swing.JInternalFrame {

    PedidosController pedidos;
    private JPanel pedidosContainer;

    public PedidosEmProcesso(PedidosController pedidos) {
        this.pedidos = pedidos;

        initComponents();

        pedidosContainer = new JPanel();
        pedidosContainer.setLayout(new BoxLayout(pedidosContainer, BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(pedidosContainer);

        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPedidos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        CancelarPedido = new javax.swing.JButton();
        FinalizarPedido = new javax.swing.JButton();

        TabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N* Pedido", "Itens", "Adicionais", "Valor total"
            }
        ));
        jScrollPane1.setViewportView(TabelaPedidos);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Voltar");

        CancelarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CancelarPedido.setText("Cancelar Pedido");
        CancelarPedido.addActionListener(this::CancelarPedidoActionPerformed);

        FinalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FinalizarPedido.setText("Concluir Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinalizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(FinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTabela() {

        pedidosContainer.removeAll();

        List<Pedidos> lista = pedidos.procurarPedidos();

        for (Pedidos p : lista) {

            DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"Produto", "Qtd", "Total"}, 0
            );

            for (ItemPedidos item : p.getItens()) {
                model.addRow(new Object[]{
                        item.getProduto().getNome(),
                        item.getQuantidade(),
                        item.getProduto().getPreco().multiply(new BigDecimal(item.getQuantidade()))
                });
            }

            JTable tabela = new JTable(model);

            JPanel painelPedido = new JPanel(new BorderLayout());
            painelPedido.setBorder(
                    BorderFactory.createTitledBorder("Pedido " + p.getId())
            );

            painelPedido.add(new JScrollPane(tabela));

            pedidosContainer.add(painelPedido);
        }

        pedidosContainer.revalidate();
        pedidosContainer.repaint();
    }
            

    private void CancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void FinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarPedidoActionPerformed

    }//GEN-LAST:event_CancelarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarPedido;
    private javax.swing.JButton FinalizarPedido;
    private javax.swing.JTable TabelaPedidos;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
