/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.Gregorys2s.view.relatorios;

import com.github.Gregorys2s.controller.RelatorioController;
import com.github.Gregorys2s.entity.RelatorioDiario;
import java.awt.*;
import java.math.BigDecimal;
import java.text.*;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.*;
import javax.swing.border.TitledBorder;

/**
 *
 * @author pedro
 */
public class RelatoriosFrame extends javax.swing.JInternalFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RelatoriosFrame.class.getName());
    private static final DateTimeFormatter FMT_DATA = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private static final NumberFormat FMT_BRL = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

    private static final Color COR_FUNDO   = new Color(245, 245, 245);
    private static final Color COR_LABEL   = new Color(80, 80, 80);
    private static final Color COR_VERDE   = new Color(34, 139, 34);
    private static final Color COR_VERMELHO = new Color(180, 30, 30);
    private static final Color COR_AZUL    = new Color(30, 100, 180);
    private static final Font FONTE_LABEL  = new Font("Segoe UI", Font.PLAIN, 13);
    private static final Font FONTE_VALOR  = new Font("Segoe UI", Font.BOLD, 13);
    private static final Font FONTE_TITULO = new Font("Segoe UI", Font.BOLD, 14);
    
    
    private JLabel lblData;
    private JLabel lblQuantidadePedidos;
    private JLabel lblDespesas;
    private JLabel lblLucroTotal;
    private JLabel lblEstoqueFinal;
    private JLabel lblLucroLiquido;
    
    private final RelatorioController relatorioController;
    /**
     * Creates new form relatoriosFrame
     */
    public RelatoriosFrame(RelatorioController relatorioController) {
        this.relatorioController = relatorioController;
        initComponents(); // Método gerado pelo Matisse
        
        configurarDiarioAtualPane(); // Acoplamento customizado do seu layout antigo
        carregarRelatorioDoDia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        diarioAtualPane = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout diarioAtualPaneLayout = new javax.swing.GroupLayout(diarioAtualPane);
        diarioAtualPane.setLayout(diarioAtualPaneLayout);
        diarioAtualPaneLayout.setHorizontalGroup(
            diarioAtualPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        diarioAtualPaneLayout.setVerticalGroup(
            diarioAtualPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Diario", diarioAtualPane);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Semanal", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pesquisar relatorio de dia", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pesquisar relatorio de semana", jPanel5);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarDiarioAtualPane() {
        // Altera o layout do painel da aba para BorderLayout para receber os dados e o botão
        diarioAtualPane.setLayout(new BorderLayout(0, 10));
        diarioAtualPane.setBackground(COR_FUNDO);
        diarioAtualPane.setBorder(BorderFactory.createEmptyBorder(14, 16, 14, 16));
        
        // Remove os jLabels genéricos (jLabel1, jLabel2...) gerados automaticamente
        diarioAtualPane.removeAll(); 
        
        // Adiciona a estrutura rica que você já possuía
        diarioAtualPane.add(criarPainelDados(), BorderLayout.CENTER);
        diarioAtualPane.add(criarPainelBotoes(), BorderLayout.SOUTH);
        diarioAtualPane.revalidate();
        diarioAtualPane.repaint();
    }

    private JPanel criarPainelDados() {
        JPanel painel = new JPanel(new GridBagLayout());
        painel.setBackground(Color.WHITE);
        painel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200)),
                "Resumo do Turno",
                TitledBorder.LEFT,
                TitledBorder.TOP,
                FONTE_TITULO,
                COR_AZUL));

        GridBagConstraints cLabel = new GridBagConstraints();
        cLabel.anchor = GridBagConstraints.WEST;
        cLabel.insets = new Insets(8, 12, 0, 8);
        cLabel.gridx = 0;

        GridBagConstraints cValor = new GridBagConstraints();
        cValor.anchor = GridBagConstraints.EAST;
        cValor.insets = new Insets(8, 0, 0, 12);
        cValor.gridx = 1;
        cValor.fill = GridBagConstraints.HORIZONTAL;
        cValor.weightx = 1.0;

        lblData               = criarLabelValor("—");
        lblQuantidadePedidos  = criarLabelValor("—");
        lblDespesas           = criarLabelValor("—", COR_VERMELHO);
        lblLucroTotal         = criarLabelValor("—", COR_VERDE);
        lblEstoqueFinal       = criarLabelValor("—");
        lblLucroLiquido       = criarLabelValor("—", COR_VERDE);

        int linha = 0;

        adicionarLinha(painel, "Data:",              lblData,              cLabel, cValor, linha++);
        adicionarSeparador(painel, linha++);
        adicionarLinha(painel, "Qtd. de Pedidos:",   lblQuantidadePedidos, cLabel, cValor, linha++);
        adicionarSeparador(painel, linha++);
        adicionarLinha(painel, "Despesas:",           lblDespesas,          cLabel, cValor, linha++);
        adicionarSeparador(painel, linha++);
        adicionarLinha(painel, "Lucro Total:",        lblLucroTotal,        cLabel, cValor, linha++);
        adicionarSeparador(painel, linha++);
        adicionarLinha(painel, "Estoque Final:",      lblEstoqueFinal,      cLabel, cValor, linha++);
        adicionarSeparador(painel, linha++);
        adicionarLinha(painel, "Lucro Líquido:",      lblLucroLiquido,      cLabel, cValor, linha++);

        GridBagConstraints cFill = new GridBagConstraints();
        cFill.gridy = linha;
        cFill.weighty = 1.0;
        painel.add(new JLabel(), cFill);

        return painel;
    }

    private JPanel criarPainelBotoes() {
        JPanel painelBotoes = new JPanel(new GridLayout(1, 2, 10, 0));
        painelBotoes.setBackground(COR_FUNDO);

        
        JButton btnAtualizar = new JButton("Atualizar");
        btnAtualizar.setFont(FONTE_VALOR);
        btnAtualizar.setFocusPainted(false);
        btnAtualizar.addActionListener(e -> carregarRelatorioDoDia());

        JButton btnFechar = new JButton("Fechar");
        btnFechar.setFont(FONTE_VALOR);
        btnFechar.setFocusPainted(false);
        btnFechar.addActionListener(e -> dispose()); 

        painelBotoes.add(btnAtualizar);
        painelBotoes.add(btnFechar);

        return painelBotoes;
    }
    private void adicionarLinha(JPanel p, String textoLabel, JLabel lblValor,
                                GridBagConstraints cL, GridBagConstraints cV, int linha) {
        JLabel label = new JLabel(textoLabel);
        label.setFont(FONTE_LABEL);
        label.setForeground(COR_LABEL);

        cL.gridy = linha;
        cV.gridy = linha;
        p.add(label,   cL);
        p.add(lblValor, cV);
    }

    private void adicionarSeparador(JPanel p, int linha) {
        GridBagConstraints c = new GridBagConstraints();
        c.gridy = linha;
        c.gridwidth = 2;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.insets = new Insets(2, 12, 0, 12);
        JSeparator sep = new JSeparator();
        sep.setForeground(new Color(220, 220, 220));
        p.add(sep, c);
    }

    private JLabel criarLabelValor(String texto) {
        return criarLabelValor(texto, Color.BLACK);
    }

    private JLabel criarLabelValor(String texto, Color cor) {
        JLabel lbl = new JLabel(texto, SwingConstants.RIGHT);
        lbl.setFont(FONTE_VALOR);
        lbl.setForeground(cor);
        return lbl;
    }

    // ── Lógica de carregamento de dados (idêntica à sua View) ─────────────────
    private void carregarRelatorioDoDia() {
        try {
            var todos = relatorioController.listarTodos();
            if (todos.isEmpty()) {
                mostrarVazio();
                return;
            }
            RelatorioDiario relatorio = todos.get(0);
            preencherCampos(relatorio);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar relatório:\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void preencherCampos(RelatorioDiario r) {
        lblData.setText(r.getData().format(FMT_DATA));
        lblQuantidadePedidos.setText(String.valueOf(r.getQuantidadePedidos()));
        lblDespesas.setText(FMT_BRL.format(r.getDespesas()));
        lblLucroTotal.setText(FMT_BRL.format(r.getLucroTotal()));

        if (r.getEstoqueFinal() != null) {
            lblEstoqueFinal.setText(FMT_BRL.format(r.getEstoqueFinal()));
        } else {
            lblEstoqueFinal.setText("—");
        }

        BigDecimal lucroLiquido = r.getLucroTotal().subtract(r.getDespesas());
        lblLucroLiquido.setText(FMT_BRL.format(lucroLiquido));
        lblLucroLiquido.setForeground(lucroLiquido.compareTo(BigDecimal.ZERO) >= 0 ? COR_VERDE : COR_VERMELHO);
    }

    private void mostrarVazio() {
        lblData.setText("Sem registro");
        lblQuantidadePedidos.setText("—");
        lblDespesas.setText("—");
        lblLucroTotal.setText("—");
        lblEstoqueFinal.setText("—");
        lblLucroLiquido.setText("—");
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diarioAtualPane;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
