package com.github.Gregorys2s.view.ingredientes;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import com.github.Gregorys2s.controller.CardapioController;
import com.github.Gregorys2s.controller.IngredientesController;
import com.github.Gregorys2s.entity.Ingredientes;
import com.github.Gregorys2s.exceptions.BttnViewException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.*;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.text.*;

/**
 *
 * @author Aluno 41
 */
public class AdicionarIngredientePanel extends javax.swing.JPanel {
    private IngredientesController ingredientesController;

    /**
     * Creates new form AdicionarItemPanel
     */
    public AdicionarIngredientePanel(IngredientesController ingredientesController) {
        this.ingredientesController = ingredientesController;
        initComponents();

        quantidadeLabel.setFocusLostBehavior(JFormattedTextField.PERSIST);

        DecimalFormat formatoDecimal = new DecimalFormat("#0.00");
        formatoDecimal.setParseBigDecimal(true);

        NumberFormatter numeroFormatado = new NumberFormatter(formatoDecimal);
        numeroFormatado.setAllowsInvalid(true);

        quantidadeLabel.setFormatterFactory(new DefaultFormatterFactory(numeroFormatado));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JFormattedTextField();
        cancelBttn = new javax.swing.JToggleButton();
        addBttn = new javax.swing.JToggleButton();
        nomeLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Nome");

        jLabel3.setText("Quantidade");

        quantidadeLabel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        quantidadeLabel.addActionListener(this::quantidadeLabelActionPerformed);

        cancelBttn.setText("Cancelar");
        cancelBttn.addActionListener(this::cancelBttnActionPerformed);

        addBttn.setText("Adicionar");
        addBttn.addActionListener(this::addBttnActionPerformed);

        nomeLabel.addActionListener(this::nomeLabelActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Novo ingrediente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(quantidadeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBttn)
                    .addComponent(addBttn))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBttnActionPerformed
        getWindowAncestor(this).dispose();
    }//GEN-LAST:event_cancelBttnActionPerformed

    private void addBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBttnActionPerformed
        try{

            Ingredientes ingredientes = new Ingredientes();

            String nome = nomeLabel.getText().trim();

            if (nome.isEmpty()) {
                throw new BttnViewException("Nome do item não pode ser vazio");
            }

            String qtdTexto = quantidadeLabel.getText().trim();

            qtdTexto = qtdTexto.replace(",", ""); // remove vírgula se o usuário errar

            if (qtdTexto.isEmpty()) {
                throw new BttnViewException("Quantidade não pode estar vazia");
            }

            int quantidade = parseQuantidade(quantidadeLabel.getText(), quantidadeLabel);

            if (quantidade <= 0) {
                throw new BttnViewException("Quantidade não pode ser menor ou igual a zero");
            }

            ingredientes.setNome(nome);
            ingredientes.setEstoque(quantidade);
            ingredientesController.cadastrarIngrediente(ingredientes);


            getWindowAncestor(this).dispose();
        }catch(BttnViewException e)
        {
            showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_addBttnActionPerformed

    private void nomeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeLabelActionPerformed

    private void quantidadeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeLabelActionPerformed

    private int parseQuantidade(String texto, JTextField campo) throws BttnViewException {
        texto = texto.trim();

        if (texto.isEmpty()) {
            campo.requestFocus();
            throw new BttnViewException("Quantidade não pode estar vazia");
        }

        if (!texto.matches("\\d+")) {
            campo.requestFocus();
            throw new BttnViewException("Digite apenas números inteiros");
        }

        return Integer.parseInt(texto);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBttn;
    private javax.swing.JToggleButton cancelBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeLabel;
    private javax.swing.JFormattedTextField quantidadeLabel;
    // End of variables declaration//GEN-END:variables
}
