package com.github.Gregorys2s.view.ingredientes;

import com.github.Gregorys2s.controller.ingredientes.Implementacoes.IngredientesController;
import com.github.Gregorys2s.model.entity.Ingredientes;
import com.github.Gregorys2s.exceptions.BttnViewException;
import com.github.Gregorys2s.controller.ingredientes.DTO.IngredientesDTO;
import com.github.Gregorys2s.view.tema.TemaSistema;

import java.text.DecimalFormat;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.text.*;

/**
 *
 * @author Aluno 41
 */
public class AdicionarIngredientePanel extends javax.swing.JPanel {
    private IngredientesController ingredientesController;

    /**
     * Creates new form AdicionarItemPanel
     */
    public AdicionarIngredientePanel(IngredientesController ingredientesController) {
        this.ingredientesController = ingredientesController;
        initComponents();
        configurarVisual();
    }

    private void configurarVisual() {
        TemaSistema.aplicar(this);
        
        jLabel2.setForeground(TemaSistema.primaria());
        jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 18));
        
        quantidadeLabel.setFocusLostBehavior(JFormattedTextField.PERSIST);

        DecimalFormat formatoDecimal = new DecimalFormat("#0");
        formatoDecimal.setParseBigDecimal(false);

        NumberFormatter numeroFormatado = new NumberFormatter(formatoDecimal);
        numeroFormatado.setAllowsInvalid(false);
        numeroFormatado.setMinimum(0);

        quantidadeLabel.setFormatterFactory(new DefaultFormatterFactory(numeroFormatado));
        
        // Ajuste de botões
        addBttn.setBackground(TemaSistema.sucesso());
        cancelBttn.setBackground(TemaSistema.secundaria());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JFormattedTextField();
        cancelBttn = new javax.swing.JToggleButton();
        addBttn = new javax.swing.JToggleButton();
        nomeLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Nome");

        jLabel3.setText("Quantidade");

        quantidadeLabel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        cancelBttn.setText("Cancelar");
        cancelBttn.addActionListener(this::cancelBttnActionPerformed);

        addBttn.setText("Adicionar");
        addBttn.addActionListener(this::addBttnActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Novo ingrediente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(quantidadeLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBttnActionPerformed
        getWindowAncestor(this).dispose();
    }//GEN-LAST:event_cancelBttnActionPerformed

    private void addBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBttnActionPerformed
        try{
            String nome = nomeLabel.getText().trim();

            if (nome.isEmpty()) {
                throw new BttnViewException("Nome do item não pode ser vazio");
            }

            String qtdTexto = quantidadeLabel.getText().trim();
            if (qtdTexto.isEmpty()) {
                throw new BttnViewException("Quantidade não pode estar vazia");
            }

            int quantidade = parseQuantidade(qtdTexto, quantidadeLabel);

            if (quantidade <= 0) {
                throw new BttnViewException("Quantidade não pode ser menor ou igual a zero");
            }
            
            IngredientesDTO dto = new IngredientesDTO();
            dto.setNome(nome);
            dto.setEstoque(quantidade);
            
            ingredientesController.cadastrarIngrediente(dto);
            
            showMessageDialog(this, "Ingrediente cadastrado com sucesso!");
            getWindowAncestor(this).dispose();
        }catch(BttnViewException e)
        {
            showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            showMessageDialog(this, "Erro ao cadastrar ingrediente: " + e.getMessage());
        }
    }//GEN-LAST:event_addBttnActionPerformed

    private int parseQuantidade(String texto, JTextField campo) throws BttnViewException {
        texto = texto.trim().replace(".", "").replace(",", "");

        if (texto.isEmpty()) {
            campo.requestFocus();
            throw new BttnViewException("Quantidade não pode estar vazia");
        }

        if (!texto.matches("\\d+")) {
            campo.requestFocus();
            throw new BttnViewException("Digite apenas números inteiros");
        }

        return Integer.parseInt(texto);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBttn;
    private javax.swing.JToggleButton cancelBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeLabel;
    private javax.swing.JFormattedTextField quantidadeLabel;
    // End of variables declaration//GEN-END:variables
}
