/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.ingredientes;

import com.github.Gregorys2s.controller.IngredientesController;
import com.github.Gregorys2s.entity.Ingredientes;
import com.github.Gregorys2s.util.LeitoresSwing;
import com.github.Gregorys2s.view.cardapio.AdicionarItemPanel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author necro
 */
public class IngredientesView extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    private IngredientesController ingredientesController;



    /**
     * Creates new form IngredientesView
     */
    public IngredientesView(JDesktopPane desktop,IngredientesController ingredientesController) {
        this.desktop = desktop;
        this.ingredientesController = ingredientesController;
        initComponents();
        carregarIngredientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        comboFiltroSelector = new javax.swing.JComboBox<>();
        stringRecebida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adicionarItemBttn = new javax.swing.JButton();
        voltarBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngredientes = new javax.swing.JTable();
        AlterarEstoque = new javax.swing.JButton();

        comboFiltroSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preço", "Nome", "Tipo", " " }));
        comboFiltroSelector.setSelectedIndex(1);
        comboFiltroSelector.addActionListener(this::comboFiltroSelectorActionPerformed);

        stringRecebida.addActionListener(this::stringRecebidaActionPerformed);
        stringRecebida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stringRecebidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stringRecebidaKeyTyped(evt);
            }
        });

        jLabel1.setText("Pesquisa:");

        jLabel2.setText("Filtro:");

        adicionarItemBttn.setText("Adicionar Item");
        adicionarItemBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adicionarItemBttnMouseReleased(evt);
            }
        });

        voltarBttn.setText("Voltar ao menu");
        voltarBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                voltarBttnMouseReleased(evt);
            }
        });
        voltarBttn.addActionListener(this::voltarBttnActionPerformed);

        tbIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Estoque"
            }
        ));
        jScrollPane1.setViewportView(tbIngredientes);

        AlterarEstoque.setText("Alterar Estoque");
        AlterarEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AlterarEstoqueMouseReleased(evt);
            }
        });
        AlterarEstoque.addActionListener(this::AlterarEstoqueActionPerformed);

        jDesktopPane1.setLayer(comboFiltroSelector, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(stringRecebida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(adicionarItemBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(voltarBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AlterarEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(adicionarItemBttn)
                        .addGap(18, 18, 18)
                        .addComponent(AlterarEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarBttn))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(stringRecebida, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(comboFiltroSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stringRecebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboFiltroSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarBttn)
                    .addComponent(adicionarItemBttn)
                    .addComponent(AlterarEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFiltroSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFiltroSelectorActionPerformed

    private void stringRecebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringRecebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringRecebidaActionPerformed

    private void stringRecebidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stringRecebidaKeyReleased

    }//GEN-LAST:event_stringRecebidaKeyReleased

    private void stringRecebidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stringRecebidaKeyTyped

    }//GEN-LAST:event_stringRecebidaKeyTyped

    private void adicionarItemBttnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarItemBttnMouseReleased
        AdicionarIngredientePanel panel = new AdicionarIngredientePanel(ingredientesController);
        Window janela = SwingUtilities.getWindowAncestor(this);

        JDialog dialogoAdd = new JDialog((Frame)janela, "Adicionar novo item", true);

        dialogoAdd.getContentPane().add(panel);
        dialogoAdd.pack();
        dialogoAdd.setLocationRelativeTo(this);
        dialogoAdd.setResizable(false);
        dialogoAdd.setVisible(true);
        carregarIngredientes();
    }//GEN-LAST:event_adicionarItemBttnMouseReleased

    private void voltarBttnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarBttnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarBttnMouseReleased

    private void voltarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarBttnActionPerformed

    private void AlterarEstoqueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarEstoqueMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarEstoqueMouseReleased

    private void AlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarEstoqueActionPerformed
        int linha = tbIngredientes.getSelectedRow();
        int id = (int) tbIngredientes.getValueAt(linha, 0);
        
        if (linha == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione algum Ingrediente");
            return;
        }
        
        Integer quantidade = LeitoresSwing.lerInteger("Digite a quantidade do novo estoque");
        
        if (quantidade == null) {
            return;
        }
        
        Ingredientes ingredientes = ingredientesController.buscarId(id);
        ingredientes.setEstoque(quantidade);
        ingredientesController.atualizarIngrediente(ingredientes.getId(),ingredientes);
        carregarIngredientes();

    }//GEN-LAST:event_AlterarEstoqueActionPerformed

    private void carregarIngredientes() {

        DefaultTableModel model = (DefaultTableModel) tbIngredientes.getModel();
        model.setRowCount(0); // limpa tabela

        for (Ingredientes i : ingredientesController.listarIngredientes()) {
            model.addRow(new Object[]{
                    i.getId(),
                    i.getNome(),
                    i.getEstoque()
            });
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarEstoque;
    private javax.swing.JButton adicionarItemBttn;
    private javax.swing.JComboBox<String> comboFiltroSelector;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stringRecebida;
    private javax.swing.JTable tbIngredientes;
    private javax.swing.JButton voltarBttn;
    // End of variables declaration//GEN-END:variables
}
