/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.ingredientes;

import com.github.Gregorys2s.controller.ingredientes.DTO.IngredientesDTO;
import com.github.Gregorys2s.controller.ingredientes.Implementacoes.IngredientesController;
import com.github.Gregorys2s.util.LeitoresSwing;
import com.github.Gregorys2s.view.tema.TemaSistema;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;

/**
 *
 * @author necro
 */
public class IngredientesView extends javax.swing.JInternalFrame {

    private JDesktopPane desktop;
    private IngredientesController ingredientesController;
    private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form IngredientesView
     */
    public IngredientesView(JDesktopPane desktop, IngredientesController ingredientesController) {
        this.desktop = desktop;
        this.ingredientesController = ingredientesController;
        initComponents();
        configurarVisual();
        carregarIngredientes();
    }

    private void configurarVisual() {
        TemaSistema.aplicar(this);
        
        // Ajustes finos após aplicação do tema
        tbIngredientes.setRowHeight(38);
        
        sorter = new TableRowSorter<>(tbIngredientes.getModel());
        tbIngredientes.setRowSorter(sorter);

        // Listener para pesquisa em tempo real
        stringRecebida.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
        
        // Melhorando o alinhamento do JScrollPane
        jScrollPane1.setBorder(BorderFactory.createLineBorder(TemaSistema.borda()));
    }

    private void filtrar() {
        String texto = stringRecebida.getText().trim();
        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        comboFiltroSelector = new javax.swing.JComboBox<>();
        stringRecebida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adicionarItemBttn = new javax.swing.JButton();
        voltarBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngredientes = new javax.swing.JTable();
        AlterarEstoque = new javax.swing.JButton();
        DeletarIngrediente = new javax.swing.JButton();

        comboFiltroSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preço", "Nome", "Tipo", " " }));
        comboFiltroSelector.setSelectedIndex(1);

        jLabel1.setText("Pesquisa:");

        jLabel2.setText("Filtro:");

        adicionarItemBttn.setText("Adicionar Item");
        adicionarItemBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adicionarItemBttnMouseReleased(evt);
            }
        });

        voltarBttn.setText("Voltar ao menu");
        voltarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBttnActionPerformed(evt);
            }
        });

        tbIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbIngredientes);

        AlterarEstoque.setText("Alterar Estoque");
        AlterarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarEstoqueActionPerformed(evt);
            }
        });

        DeletarIngrediente.setText("Deletar ingrediente");
        DeletarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarIngredienteActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(comboFiltroSelector, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(stringRecebida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(adicionarItemBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(voltarBttn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(AlterarEstoque, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(DeletarIngrediente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(adicionarItemBttn)
                        .addGap(18, 18, 18)
                        .addComponent(AlterarEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(DeletarIngrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarBttn))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stringRecebida, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFiltroSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stringRecebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboFiltroSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarBttn)
                    .addComponent(adicionarItemBttn)
                    .addComponent(AlterarEstoque)
                    .addComponent(DeletarIngrediente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarItemBttnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarItemBttnMouseReleased
        AdicionarIngredientePanel panel = new AdicionarIngredientePanel(ingredientesController);
        Window janela = SwingUtilities.getWindowAncestor(this);

        JDialog dialogoAdd = new JDialog((Frame)janela, "Adicionar novo item", true);

        dialogoAdd.getContentPane().add(panel);
        dialogoAdd.pack();
        dialogoAdd.setLocationRelativeTo(this);
        dialogoAdd.setResizable(false);
        dialogoAdd.setVisible(true);
        carregarIngredientes();
    }//GEN-LAST:event_adicionarItemBttnMouseReleased

    private void voltarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarBttnActionPerformed

    private void AlterarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarEstoqueActionPerformed
        int linha = tbIngredientes.getSelectedRow();

        if (linha == -1){
            JOptionPane.showMessageDialog(this, "Selecione um ingrediente na tabela.");
            return;
        }

        int id = (int) tbIngredientes.getValueAt(linha, 0);

        Integer quantidade = LeitoresSwing.lerInteger("Digite a quantidade do novo estoque");
        
        if (quantidade == null) {
            return;
        }

        IngredientesDTO ingredientes = ingredientesController.buscarId(id);
        if (ingredientes != null) {
            ingredientes.setEstoque(quantidade);
            ingredientesController.atualizarIngrediente(ingredientes.getId(), ingredientes);
            carregarIngredientes();
        }
    }//GEN-LAST:event_AlterarEstoqueActionPerformed

    private void DeletarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarIngredienteActionPerformed
        int linha = tbIngredientes.getSelectedRow();

        if(linha == -1){
            JOptionPane.showMessageDialog(this, "Selecione um ingrediente na tabela.");
            return;
        }

        int id = (int) tbIngredientes.getValueAt(linha, 0);
        
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este ingrediente?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            ingredientesController.excluirIngrediente(id);
            carregarIngredientes();
        }
    }//GEN-LAST:event_DeletarIngredienteActionPerformed

    private void carregarIngredientes() {
        DefaultTableModel model = (DefaultTableModel) tbIngredientes.getModel();
        model.setRowCount(0);

        for (IngredientesDTO i : ingredientesController.listarIngredientes()) {
            model.addRow(new Object[]{
                    i.getId(),
                    i.getNome(),
                    i.getEstoque()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarEstoque;
    private javax.swing.JButton DeletarIngrediente;
    private javax.swing.JButton adicionarItemBttn;
    private javax.swing.JComboBox<String> comboFiltroSelector;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stringRecebida;
    private javax.swing.JTable tbIngredientes;
    private javax.swing.JButton voltarBttn;
    // End of variables declaration//GEN-END:variables
}
