/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.Gregorys2s.view.cardapio;

import com.github.Gregorys2s.controller.cardapio.Implementacoes.CardapioController;
import com.github.Gregorys2s.exceptions.BttnViewException;
import com.github.Gregorys2s.view.tema.TemaSistema;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.*;
import java.awt.*;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.text.*;

/**
 *
 * @author Aluno 41
 */
public class AdicionarItemPanel extends javax.swing.JPanel {
    private CardapioController cardapioController;

    /**
     * Creates new form AdicionarItemPanel
     */
    public AdicionarItemPanel(CardapioController cardapioController) {
        this.cardapioController = cardapioController;
        initComponents();
        configurarVisual();
    }

    private void configurarVisual() {
        TemaSistema.aplicar(this);
        
        jLabel4.setForeground(TemaSistema.primaria());
        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 18));
        
        precoLabel.setFocusLostBehavior(JFormattedTextField.PERSIST);
    
        DecimalFormat formatoDecimal = new DecimalFormat("#0.00");
        formatoDecimal.setParseBigDecimal(true);
        
        NumberFormatter numeroFormatado = new NumberFormatter(formatoDecimal);
        numeroFormatado.setAllowsInvalid(true);
        
        precoLabel.setFormatterFactory(new DefaultFormatterFactory(numeroFormatado));
        precoLabel.setValue(BigDecimal.ZERO);
        
        addBttn.setBackground(TemaSistema.sucesso());
        cancelBttn.setBackground(TemaSistema.secundaria());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precoLabel = new javax.swing.JFormattedTextField();
        cancelBttn = new javax.swing.JToggleButton();
        addBttn = new javax.swing.JToggleButton();
        nomeLabel = new javax.swing.JTextField();
        tipoComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Nome do Item:");

        jLabel2.setText("Tipo do Item:");

        jLabel3.setText("Preço do Item:");

        precoLabel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        cancelBttn.setText("Cancelar");
        cancelBttn.addActionListener(this::cancelBttnActionPerformed);

        addBttn.setText("Adicionar");
        addBttn.addActionListener(this::addBttnActionPerformed);

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lanche", "Combo", "Bebida", "Porção" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Novo Produto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precoLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBttnActionPerformed
        getWindowAncestor(this).dispose();
    }//GEN-LAST:event_cancelBttnActionPerformed

    private void addBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBttnActionPerformed
        try{
            String nome = nomeLabel.getText().trim();
            
            if(nome.isEmpty()){throw new BttnViewException("Nome do item não pode ser vazio");}
            String tipo = tipoComboBox.getSelectedItem().toString();

            String precoTexto = precoLabel.getText().trim();
            
            if(precoTexto.isEmpty()){throw new BttnViewException("O preço não pode estar vazio");}
            
            String valorFormatado = precoTexto.replace(".", "").replace(",", ".");
            BigDecimal valor = new BigDecimal(valorFormatado);

            if(valor.compareTo(BigDecimal.ZERO) <= 0.0){throw new BttnViewException("Valor não pode ser menor ou igual a zero");}
            
            BigDecimal valorArredondado = valor.setScale(2, RoundingMode.HALF_UP);
            cardapioController.adicionarItem(nome, tipo, valorArredondado);

            showMessageDialog(this, "Produto adicionado com sucesso!");
            getWindowAncestor(this).dispose();
        }catch(BttnViewException e)
        {
            showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            showMessageDialog(this, "Erro ao adicionar produto: " + e.getMessage());
        }
    }//GEN-LAST:event_addBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addBttn;
    private javax.swing.JToggleButton cancelBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeLabel;
    private javax.swing.JFormattedTextField precoLabel;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
