/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.Gregorys2s.view.cardapio;

import com.github.Gregorys2s.controller.cardapio.Implementacoes.CardapioController;
import com.github.Gregorys2s.exceptions.BttnViewException;
import com.github.Gregorys2s.view.tema.TemaSistema;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.*;
import java.awt.*;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.SwingUtilities.getWindowAncestor;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author pedro
 */
public class EditarItemPanel extends javax.swing.JPanel {
    private final CardapioController cardapioController;
    private Integer id;
    private int contTemp = 0;
    /**
     * Creates new form EditarItemPanel
     */
    public EditarItemPanel(CardapioController cardapioController, Integer id) {
        this.cardapioController = cardapioController;
        this.id = id;
        initComponents();
        configurarVisual();
    }

    private void configurarVisual() {
        TemaSistema.aplicar(this);
        
        nomeItem.setText(cardapioController.retornarNome(id));
        nomeItem.setForeground(TemaSistema.primaria());
        
        precoLabel.setFocusLostBehavior(JFormattedTextField.PERSIST);
    
        DecimalFormat formatoDecimal = new DecimalFormat("#0.00");
        formatoDecimal.setParseBigDecimal(true);
        
        NumberFormatter numeroFormatado = new NumberFormatter(formatoDecimal);
        numeroFormatado.setAllowsInvalid(true);
        
        precoLabel.setFormatterFactory(new DefaultFormatterFactory(numeroFormatado));
        precoLabel.setValue(BigDecimal.ZERO);
        precoLabel.setEnabled(false);
        
        confirmBttn.setBackground(TemaSistema.sucesso());
        cancelBttn.setBackground(TemaSistema.secundaria());
        jToggleButton4.setBackground(TemaSistema.perigo());
        
        // Estilizando CheckBoxes
        nomeCheck.setOpaque(false);
        precoCheck.setOpaque(false);
        tipoCheck.setOpaque(false);
        nomeCheck.setForeground(TemaSistema.texto());
        precoCheck.setForeground(TemaSistema.texto());
        tipoCheck.setForeground(TemaSistema.texto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCheck = new javax.swing.JCheckBox();
        precoCheck = new javax.swing.JCheckBox();
        tipoCheck = new javax.swing.JCheckBox();
        cancelBttn = new javax.swing.JToggleButton();
        confirmBttn = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        nomeLabel = new javax.swing.JTextField();
        nomeItem = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        precoLabel = new javax.swing.JFormattedTextField();

        nomeCheck.setText("Alterar nome");
        nomeCheck.addItemListener(this::nomeCheckItemStateChanged);

        precoCheck.setText("Alterar preço");
        precoCheck.addItemListener(this::precoCheckItemStateChanged);

        tipoCheck.setText("Alterar tipo");
        tipoCheck.addItemListener(this::tipoCheckItemStateChanged);

        cancelBttn.setText("Cancelar");
        cancelBttn.addActionListener(this::cancelBttnActionPerformed);

        confirmBttn.setText("Confirmar");
        confirmBttn.addActionListener(this::confirmBttnActionPerformed);

        jToggleButton4.setText("Deletar");
        jToggleButton4.addActionListener(this::jToggleButton4ActionPerformed);

        nomeLabel.setEnabled(false);

        nomeItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeItem.setText("jLabel1");

        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lanche", "Combo", "Bebida", "Porção" }));
        tipoComboBox.setEnabled(false);

        precoLabel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(precoCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(precoLabel)
                            .addComponent(tipoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nomeItem)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCheck)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCheck)
                    .addComponent(precoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCheck)
                    .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBttnActionPerformed
        getWindowAncestor(this).dispose();
    }//GEN-LAST:event_cancelBttnActionPerformed

    private void nomeCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomeCheckItemStateChanged
        if(nomeCheck.isSelected())
        {
            nomeLabel.setEnabled(true);
            nomeLabel.requestFocus();
            contTemp++;
        } else {
            nomeLabel.setEnabled(false);
            nomeLabel.setText("");
            contTemp--;
        }
    }//GEN-LAST:event_nomeCheckItemStateChanged

    private void precoCheckItemStateChanged(java.awt.event.ItemEvent evt) {
        if(precoCheck.isSelected())
        {
            precoLabel.setEnabled(true);
            precoLabel.requestFocus();
            contTemp++;
        } else {
            precoLabel.setEnabled(false);
            precoLabel.setText("");
            contTemp--;
        }
    }

    private void tipoCheckItemStateChanged(java.awt.event.ItemEvent evt) {
       if(tipoCheck.isSelected())
        {
            tipoComboBox.setEnabled(true);
            tipoComboBox.requestFocus();
            contTemp++;
        } else {
            tipoComboBox.setEnabled(false);
            contTemp--;
        }
    }

    private void confirmBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBttnActionPerformed
        try{
            var produtoOriginal = cardapioController.produtoSelecionadoId(id);
            String nome = produtoOriginal.getNome();
            String tipo = produtoOriginal.getTipo();
            BigDecimal valor = produtoOriginal.getPreco();
            
            if(nomeCheck.isSelected())
            {
                nome = nomeLabel.getText().trim();
                if(nome.isEmpty()){throw new BttnViewException("Nome do item não pode ser vazio");}
            }
            
            if(precoCheck.isSelected())
            {
                String valorNaoFormatado = precoLabel.getText().trim();

                if(valorNaoFormatado.isEmpty()){throw new BttnViewException("Valor não pode estar vazio");}

                String valorFormatado = valorNaoFormatado.replace(".", "").replace(",", ".");
                valor = new BigDecimal(valorFormatado);

                if(valor.compareTo(BigDecimal.ZERO) <= 0.0){throw new BttnViewException("Valor não pode ser menor ou igual a zero");}

                valor = valor.setScale(2, RoundingMode.HALF_UP);
            }
            
            if(tipoCheck.isSelected())
            {
                tipo = tipoComboBox.getSelectedItem().toString().trim();
            }
            
            if(contTemp > 0)
            {
                cardapioController.atualizarItem(id, nome, tipo, valor);
                showMessageDialog(this, "Item atualizado com sucesso!");
                getWindowAncestor(this).dispose();
            } else {
                showMessageDialog(this, "Nenhuma alteração selecionada!");
            }
            
        }catch(BttnViewException e)
        {
            showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            showMessageDialog(this, "Erro ao atualizar item: " + e.getMessage());
        }
    }//GEN-LAST:event_confirmBttnActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este item do cardápio?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // cardapioController.excluirItem(id); // Se houver método de exclusão
            showMessageDialog(this, "Funcionalidade de exclusão não implementada no controller.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelBttn;
    private javax.swing.JToggleButton confirmBttn;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JCheckBox nomeCheck;
    private javax.swing.JLabel nomeItem;
    private javax.swing.JTextField nomeLabel;
    private javax.swing.JCheckBox precoCheck;
    private javax.swing.JFormattedTextField precoLabel;
    private javax.swing.JCheckBox tipoCheck;
    private javax.swing.JComboBox<String> tipoComboBox;
    // End of variables declaration//GEN-END:variables
}
