/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.github.Gregorys2s.view.cardapio;

import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author pedro
 */
public class EditarItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarItemPanel
     */
    public EditarItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCheck = new javax.swing.JCheckBox();
        precoCheck = new javax.swing.JCheckBox();
        tipoCheck = new javax.swing.JCheckBox();
        cancelBttn = new javax.swing.JToggleButton();
        confirmBttn = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        nomeItem = new java.awt.Label();
        nomeString = new javax.swing.JTextField();
        precoString = new javax.swing.JTextField();
        tipoString = new javax.swing.JTextField();

        nomeCheck.setBackground(new java.awt.Color(255, 0, 102));
        nomeCheck.setText("Alterar nome");
        nomeCheck.addActionListener(this::nomeCheckActionPerformed);

        precoCheck.setBackground(new java.awt.Color(255, 255, 153));
        precoCheck.setText("Alterar preço");

        tipoCheck.setBackground(new java.awt.Color(51, 51, 255));
        tipoCheck.setText("Alterar tipo");

        cancelBttn.setText("Cancelar");
        cancelBttn.addActionListener(this::cancelBttnActionPerformed);

        confirmBttn.setText("Confirmar");

        jToggleButton4.setText("Deletar");

        nomeItem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nomeItem.setName(""); // NOI18N
        nomeItem.setText("label1");

        nomeString.addActionListener(this::nomeStringActionPerformed);

        precoString.addActionListener(this::precoStringActionPerformed);

        tipoString.addActionListener(this::tipoStringActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precoString, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeString)
                            .addComponent(tipoString))
                        .addGap(76, 76, 76))))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(nomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBttn)
                    .addComponent(cancelBttn)
                    .addComponent(jToggleButton4))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomeStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeStringActionPerformed

    private void precoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoStringActionPerformed

    private void tipoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoStringActionPerformed

    private void cancelBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBttnActionPerformed
        getWindowAncestor(this).dispose();
    }//GEN-LAST:event_cancelBttnActionPerformed

    private void nomeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cancelBttn;
    private javax.swing.JToggleButton confirmBttn;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JCheckBox nomeCheck;
    private java.awt.Label nomeItem;
    private javax.swing.JTextField nomeString;
    private javax.swing.JCheckBox precoCheck;
    private javax.swing.JTextField precoString;
    private javax.swing.JCheckBox tipoCheck;
    private javax.swing.JTextField tipoString;
    // End of variables declaration//GEN-END:variables
}
