/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.github.Gregorys2s.view.Pagamentos;

/**
 *
 * @author Gregory
 */
public class PagamentoView extends javax.swing.JInternalFrame {

    private String metodoPagamento;
    
    /**
     * Creates new form Pagamento
     */
    public PagamentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pixbton = new javax.swing.JButton();
        Debito = new javax.swing.JButton();
        Credito = new javax.swing.JButton();
        Dinheiro = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Escolha o metodo de pagamento");

        Pixbton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Pixbton.setText("Pix");
        Pixbton.addActionListener(this::PixbtonActionPerformed);

        Debito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Debito.setText("Debito");
        Debito.addActionListener(this::DebitoActionPerformed);

        Credito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Credito.setText("Credito");
        Credito.addActionListener(this::CreditoActionPerformed);

        Dinheiro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Dinheiro.setText("dinheiro");
        Dinheiro.addActionListener(this::DinheiroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Pixbton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Debito, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pixbton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Debito, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Credito, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PixbtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PixbtonActionPerformed
        metodoPagamento = "PIX";

        this.dispose();
    }//GEN-LAST:event_PixbtonActionPerformed

    private void DebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoActionPerformed
        metodoPagamento = "DEBITO";
    this.dispose();
    }//GEN-LAST:event_DebitoActionPerformed

    private void CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoActionPerformed
        metodoPagamento = "CREDITO";
    this.dispose();
    }//GEN-LAST:event_CreditoActionPerformed

    private void DinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DinheiroActionPerformed
    metodoPagamento = "DINHEIRO";
    this.dispose();
    }//GEN-LAST:event_DinheiroActionPerformed

    public String getMetodoPagamento() {
    return metodoPagamento;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Credito;
    private javax.swing.JButton Debito;
    private javax.swing.JButton Dinheiro;
    private javax.swing.JButton Pixbton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
